hold_button_url: https://myaccount.qa.k8s.libraries.psu.edu/holds/new?catkey=
sirsi_url: https://cat.libraries.psu.edu:28443/symwsbc/rest/standard/lookupTitleInfo?clientID=PSUCATALOG&includeAvailabilityInfo=true&includeItemInfo=true
matomo_id: 10
mysql:
  host: 127.0.0.1
datadog:
  enabled: false
  # defaults to Rails.env. override here
  # env: feature-foo
user_header: HTTP_X_AUTH_REQUEST_EMAIL
groups_header: HTTP_X_AUTH_REQUEST_GROUPS
admin_group: umg-up.ul-dev-team
redis:
  sessions:
    uri: redis://127.0.0.1:6379/3
    ttl: 86400 # 24-hours in seconds
report_issue_email_recipient: test@test.com
search_history_window: 50
solr:
  protocol: "http"
  host: "127.0.0.1"
  port: 8983
  # username:
  # password: 
  # url: http://127.0.0.1:8983
  collection: psul_catalog
hide_announcement: false
announcement:
  # See https://fontawesome.com/icons
  icon: fa-exclamation-circle
  message: 'Planned maintenance: Realtime availability, "I Want It," and My Account will be unavailable between 6 and 7am on Thursday February 23, 2023'
  html_class: bg-warning